# Generated by Django 2.1.2 on 2018-10-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_server', '0002_codea000100_codea000640_codea001630_codea006280_codea008930_codea009290_codea069620_codea096760_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='A000100',
            fields=[
                ('stock_index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stock_date', models.BigIntegerField(blank=True, null=True)),
                ('stock_time', models.BigIntegerField(blank=True, null=True)),
                ('stock_price', models.BigIntegerField(blank=True, null=True)),
                ('stock_volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'a000100',
                'managed': False,
            },
        ),
    ]
